package ConcatModule;


/**
* ConcatModule/Concat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Monday, 29 May 2023 23:29:56 o'clock IST
*/

public interface Concat extends ConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concat
