package ConcatModule;


/**
* ConcatModule/ConcatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Monday, 29 May 2023 23:29:56 o'clock IST
*/

public interface ConcatOperations 
{
  String concat (String s1, String s2);
} // interface ConcatOperations
