package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Monday, 29 May 2023 23:09:06 o'clock IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
} // interface CalculatorOperations
