package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Saturday, 13 May 2023 14:22:42 o'clock IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
